services:
  laravel:
    image: php:8.1-fpm
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./laravel/public:/var/www/laravel/public
  user-service:
    build: ./user_service
    ports:
      - "8081:8081"
    depends_on:
      - timescaledb_2
  market-service:
    build: ./market_service
    ports:
      - "8082:8082"
    depends_on:
      - timescaledb_2
  order-service:
    build: ./order_service

    ports:
      - "8083:8083"
    depends_on:
      - timescaledb_2
  timescaledb_2:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: market_service
      POSTGRES_USER: rumike
      POSTGRES_PASSWORD: 
  