services:
  # laravel:
  #   image: php:8.1-fpm
  #   volumes:
  #     - ./laravel:/var/www/portfolio
  #   depends_on:
  #     - nginx
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./laravel/public:/var/www/laravel/public

  timescaledb:
    build:
      context: .
      dockerfile: timescaledb/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simtrade_db
      POSTGRES_USER: rumike
      POSTGRES_PASSWORD: do0rdie
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rumike", "-d", "simtrade_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - simtrade-network

  builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
    image: simtrade-builder
    command: mvn clean package -DskipTests
    # volumes:
      # - ./target:/app/target
    networks:
      - simtrade-network

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    volumes:
      - ./user_service/src/main:/app/src/main
      - ./user_service/target/classes:/app/target/classes
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/simtrade_db
      SPRING_DATASOURCE_USERNAME: rumike
      SPRING_DATASOURCE_PASSWORD: do0rdie
    networks:
      - simtrade-network

  order-service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - "8083:8080"
    volumes:
      - ./order_service/src/main:/app/src/main
      - ./order_service/target/classes:/app/target/classes
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/simtrade_db
      SPRING_DATASOURCE_USERNAME: rumike
      SPRING_DATASOURCE_PASSWORD: do0rdie
    networks:
      - simtrade-network

  market-service:
    build:
      context: .
      dockerfile: market_service/Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - "8082:8080"
    volumes:
      - ./market_service/src/main:/app/src/main
      - ./market_service/target/classes:/app/target/classes
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/simtrade_db
      SPRING_DATASOURCE_USERNAME: rumike
      SPRING_DATASOURCE_PASSWORD: do0rdie
    networks:
      - simtrade-network

networks:
  simtrade-network:
    driver: bridge

volumes:
  timescaledb_data:


  # test-runner:
  #   build: ./common
  #   depends_on:
  #     - timescaledb_2
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb_2:5432/market_service
  #     SPRING_DATASOURCE_USERNAME: rumike
  #     SPRING_DATASOURCE_PASSWORD: 
  #   command: ./mvnw test
  