spring:
  application.name: order-service
  server:
    port: 8083
  datasource:
    url: jdbc:postgresql://localhost:5433/market_service
    username: rumike
    password: do0rdie
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  cloud:
    task:
      enabled: false


jwt:
  secret: fqU9JzNw9mRv0jRg5UZdg08SOunqfS406ReqAsIKpPCwk0UVyU0TNHlCIVrBfj8tUlwi2paaTXq8I2FdN1a6HA==
  expiration: 864000000

redis: 
  host: localhost 
  port: 6379

kafka: 
  bootstrap-servers: localhost:9092 
  consumer: 
    group-id: leaderboard-group 
    auto-offset-reset: latest

logging:
  level:
    com.simtrade.order_service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG


market:
  service:
    url: http://localhost:8082

user:
  service:
    url: http://localhost:8081

order:
  service:
    url: http://localhost:8083